### ISSUE TITLE
The thumbnail has a black line on the right side

### ISSUE THREAD

**Issue by StoyanStAtanasov** [onildoaguiar/image-thumbnail#100]
![image](https://github.com/user-attachments/assets/8cebecd4-e6d7-4ce9-89d3-edb674df8be4)

**Comment by StoyanStAtanasov** [comment]
Just to add, that the original image does not have a black bar on the right:
![image](https://github.com/user-attachments/assets/d9b5bcb7-9ce0-4015-a125-792e2bf0c9c1)

**Comment by onildoaguiar** [comment]
Hi @StoyanStAtanasov , I believe this issue should be raised in the [Sharp](https://github.com/lovell/sharp) repository. This library is just a wrapper.

**Comment by StoyanStAtanasov** [comment]
@onildoaguiar If I raise this issue directly with Sharp, they might need specific details on how this library is implementing their functionality.
