### ISSUE TITLE
npm module not working

### ISSUE THREAD

**Issue by Dgiulian** [onildoaguiar/image-thumbnail#2]
I've installed the package using 
`npm install thumbnail`
but when I try to require it, node couldn't resolve it.
Looking the node_modules folder I realized the `index.js` file is inside the `src/` folder. That's why node can't find it. 
Perhaps its an issue with the npm package.

**Comment by beyondinfinity01** [comment]
yeah , when i added path inside the package.json , node detected the package

**Comment by piotrzarzycki21** [comment]
@beyondinfinity01 What do you mean by adding path ? Can you clarify this a bit.

**Comment by onildoaguiar** [comment]
Thanks all for the feedback. The issue was fixed in the new version of the npm package, 1.0.1.
