### ISSUE TITLE
Possibility to keep aspect ratio

### ISSUE THREAD

**Issue by bartbutenaers** [onildoaguiar/image-thumbnail#20]
Dear Onildo (@onildoaguiar),

Thanks for sharing this node! 
I was wondering if it is possible to maintain the aspect ratio when resizing?  
So only specifying the width, but not the height.

Kind regards,
Bart Butenaers

**Comment by onildoaguiar** [comment]
Hello @bartbutenaers,

Currently, no. I validated if it has the two aspects to use in the options. But I will update the package to support only one of the two aspects in the options. Wait for the new version.

Thank you so much for the feedback,
Onildo

**Comment by bartbutenaers** [comment]
Hi @onildoaguiar,
Thanks for your (super)fast response! 
Hope to hear from you soon.
Bart

**Comment by bartbutenaers** [comment]
Thanks a lot !!
