### ISSUE TITLE
× TypeError: sharp.format is not a function

### ISSUE THREAD

**Issue by gauravkrp** [onildoaguiar/image-thumbnail#27]
I am trying to generate thumbnail for images retrieved from a s3 storage.

const imageThumbnail = require('image-thumbnail');
let options = { width: 100, height: 100, jpegOptions : { force:true, quality:80 } }
                      imageThumbnail(menuItems[idx].menuPicURL, options) //options
                       .then(thumbnail => { console.log(thumbnail) })
                      .catch(err => console.error(err));

But I'm always getting this error: sharp.format is not a function
I also installed dependencies on my own - sharp, axios, image-size and validator
But nothing works...

See screenshot:

![image](https://user-images.githubusercontent.com/12250556/72152921-6e9aaa00-33d2-11ea-81e1-50f8c15ece86.png)

**Comment by onildoaguiar** [comment]
@gauravkrp 
It's weird. Do you still have this error?
What is your version of the image-thumbnail package?

 I'll take a look.

**Comment by gauravkrp** [comment]
Yes. I'm still facing the error. I had just the updated latest version. Earlier, it was the last version being used. But the same issue is there.

The strange thing is I get this error as soon as I write the below code. Other codes are still commented.
`const imageThumbnail = require('image-thumbnail');
`
My further codes are commented.
`
let options = { width: 100, height: 100, jpegOptions : { force:true, quality:80 } }
imageThumbnail(menuItems[idx].menuPicURL, options) //options
.then(thumbnail => { console.log(thumbnail) })
.catch(err => console.error(err));
`

![image](https://user-images.githubusercontent.com/12250556/74472686-5e418780-4ec8-11ea-8647-b5831a938c93.png)

**Comment by gauravkrp** [comment]
> @gauravkrp
> It's weird. Do you still have this error?
> What is your version of the image-thumbnail package?
> 
> I'll take a look.

My package.json in a create react app -- 

```
{
  "name": "mapp",
  "version": "0.1.0",
  "private": true,
  "homepage": "",
  "author": "Gaurav Pandey",
  "dependencies": {
    "axios": "^0.19.2",
    "bootstrap": "^4.4.1",
    "formik": "^2.1.4",
    "image-size": "^0.8.3",
    "image-thumbnail": "^1.0.7",
    "immer": "^5.3.6",
    "immutability-helper": "^3.0.1",
    "jwt-decode": "^2.2.0",
    "lottie-react-web": "^2.1.4",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.27",
    "node-sass": "^4.13.1",
    "query-string": "^6.11.0",
    "react": "^16.12.0",
    "react-async": "^10.0.0",
    "react-datepicker": "^2.12.1",
    "react-dom": "^16.12.0",
    "react-easy-state": "^6.1.3",
    "react-geocode": "^0.2.1",
    "react-google-autocomplete": "^1.1.2",
    "react-google-maps": "^9.4.5",
    "react-helmet": "^5.2.1",
    "react-load-script": "0.0.6",
    "react-moment": "^0.9.7",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.2.0",
    "react-select": "^3.0.8",
    "react-slick": "^0.25.2",
    "react-tooltip": "^3.11.6",
    "sharp": "^0.24.0",
    "slick-carousel": "^1.8.1",
    "validator": "^12.2.0",
    "webfontloader": "^1.6.28",
    "yup": "^0.27.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

**Comment by onildoaguiar** [comment]
Hello @gauravkrp 

I think this error is related to `node-gyp` from `sharp` lib.

This error is common on Windows OS. Try the below instructions: 
https://github.com/nodejs/node-gyp#installation

Issue for this error from sharp lib:
https://github.com/lovell/sharp/issues/1496

I waiting for your feedback.

**Comment by gauravkrp** [comment]
> Hello @gauravkrp
> 
> I think this error is related to `node-gyp` from `sharp` lib.
> 
> This error is common on Windows OS. Try the below instructions:
> https://github.com/nodejs/node-gyp#installation
> 
> Issue for this error from sharp lib:
> [lovell/sharp#1496](https://github.com/lovell/sharp/issues/1496)
> 
> I waiting for your feedback.

I tried the steps related to `node-gyp` but no help. Error is still there.

**Comment by devakone** [comment]
Running into the same issue as well with create-react-app

**Comment by DieMyst** [comment]
Same issue with ELM app

**Comment by DieMyst** [comment]
Ah, it is quite simple
https://github.com/lovell/sharp/issues/1807
sharp is not working in a browser

**Comment by onildoaguiar** [comment]
@DieMyst Thanks for the reponse!

**Comment by mgd722** [comment]
Wait so is the takeaway here that `image-thumbnail` cannot be used in web applications? If so that probably should be made more clear somewhere on the homepage.
