### ISSUE TITLE
Error: Attempt to access memory outside buffer bounds

### ISSUE THREAD

**Issue by DangerN** [onildoaguiar/image-thumbnail#31]
Hello,

I am writing a media server using express and I need to generate thumbnails when a file is uploaded. I am only working with jpegs at the moment.

``` 
app.post('/media', (req, res) => {
  let name = req.get('File-Name')
  let ext = req.get('File-Extension')
  let buffer = Buffer.from(req.body)

  fs.mkdir(__dirname + `/media/${name}/`, (err) => {
    if (err.code === 'EEXIST') {
      console.log('Please don\'t write over things.')
    } else {
      throw err
    }

    fs.writeFile(__dirname + `/media/${name}/${name}.${ext}`, buffer, (err) => {
      if (err) {throw err}
      imageThumbnail(`./media/${name}/${name}.${ext}`)
        .then(thumb=>{console.log(thumbnail)})
        .catch(err=>console.log(err))
      res.send('seems ok')
    })

  })
})
```

I have the same error if I call ``imageThumbnail(__dirname + `/media/${name}/${name}.${ext}`)``

Perhaps I'm doing something wrong? Thank you.

**Comment by onildoaguiar** [comment]
Hello @DangerN !
Sounds good for me your implementation. But if you have the buffer, you can use it directly.

Try it:
` imageThumbnail(buffer)
        .then(thumb=>{console.log(thumbnail)})
        .catch(err=>console.log(err))
      res.send('seems ok')`

**Comment by DangerN** [comment]
Thank you for the swift reply @onildoaguiar!

That seemed to do the trick!
