### ISSUE TITLE
Force | Detect dimensions

### ISSUE THREAD

**Issue by cpecorari** [onildoaguiar/image-thumbnail#37]
Thanks for your module, however may I suggest you don't force dimensions as Sharp does get it well and `sizeOf` cant get it well on my buffer source ?
I modified your code in `getDimensions` to : 
```js
 if (typeof dimensions.width != 'undefined' || typeof dimensions.height != 'undefined') {
        return { width: dimensions.width, height: dimensions.height };
    }
```
Cheers 👍

**Comment by onildoaguiar** [comment]
@cpecorari  Thanks for the feedback! I fixed this bug in version 1.0.9.
