### ISSUE TITLE
VipsJpeg issue on some images

### ISSUE THREAD

**Issue by ShahoG** [onildoaguiar/image-thumbnail#39]
Getting this when trying to run on a JPEG from a Samsung S8 (SM-G950F):
```
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: out of order read at line 0
```
Probably linked to https://github.com/lovell/sharp/issues/1578

**Comment by onildoaguiar** [comment]
@ShahoG Thanks for the contribution. The fix will available in the version 1.0.11.
