### ISSUE TITLE
Update axios to patch security vulnerability

### ISSUE THREAD

**Issue by pwillcode** [onildoaguiar/image-thumbnail#53]
This package recently started to get a high severity rating on `npm audit` due to the following advisory:
https://npmjs.com/advisories/1594

Updating axios to at least version 0.21.1 should resolve the problem.

**Comment by pwillcode** [comment]
https://github.com/onildoaguiar/image-thumbnail/pull/52

I just saw that dependabot generated a PR for this.

**Comment by janbrogger** [comment]
Any progress on this? It's a high severity warning.

**Comment by onildoaguiar** [comment]
Fixed. Thanks for the contribution! 🚀
