### ISSUE TITLE
Having security issue in axios package

### ISSUE THREAD

**Issue by komalpcg** [onildoaguiar/image-thumbnail#63]
Received warning on installing this package: 
![image](https://user-images.githubusercontent.com/67403768/129568053-c62330ea-6399-4461-ba84-4477ada738cf.png)

Should upgrade axios to latest version

**Comment by perryjm** [comment]
Came here to report this - and see it's already reported. Love the package

**Comment by Bonnev** [comment]
This issue was already reported ago and even fixed in #57 on May 5th, upgrading the package version to 1.0.14. However, this new version was not published so we still can't upgrade..

**Comment by mhamann** [comment]
@onildoaguiar can you publish 1.0.14 to pull in these security patches?

**Comment by onildoaguiar** [comment]
New version published on npm.
