### ISSUE TITLE
Update sharp to 0.28

### ISSUE THREAD

**Issue by worksofliam** [onildoaguiar/image-thumbnail#65]
Based on this issue, is it possible to upgrade sharp to 0.28?

https://github.com/lovell/sharp/issues/2460#issuecomment-811046375

**Comment by worksofliam** [comment]
I see the commit has been made, but no release on npm.

**Comment by worksofliam** [comment]
For now, pointing at master in my `package.json`

```
"image-thumbnail": "onildoaguiar/image-thumbnail",
```

**Comment by onildoaguiar** [comment]
Hello! New version released on npm.
