### ISSUE TITLE
Sharp Error using imagethumbnail in typescript?

### ISSUE THREAD

**Issue by grapevinegizmos** [onildoaguiar/image-thumbnail#72]
Hi Id like to use this in an Angular application, but having trouble figuring out how.

I can get hold of a file object using the input element's "file" type, but that gives me a file reference not a path.  And the stream it produces doesn't seem compatible with imageThumgnail

Here's what I tried. On my webpage I have  the following:

 `<div>Image thumbnail: <input type="file" (change)="makeThumbnail($event)"></div>`

Because I can't get the full path in the browser, in my angular component I tried this:
 
```
  async makeThumbnail(evt : Event) {
    let target : HTMLInputElement = evt.target as HTMLInputElement;
    let file : File = target.files[0];
    let stream = file.stream()
    let buffer = await stream.getReader().read();
    let thumbnail = await imageThumbnail(buffer);
    console.log(thumbnail);     
  }

```
But that won't compile.  How to do this properly?

**Comment by grapevinegizmos** [comment]
After some experimentation I revised to this:

 ```
async makeThumbnail(evt : Event) {
    let target : HTMLInputElement = evt.target as HTMLInputElement;
    let file : File = target.files[0];
    let url = URL.createObjectURL((file))
    console.log(url);
    let thumbnail = imageThumbnail(url);  
  }
```
which at least compiles, but fails with a bunch of error messages which I don't understand.

`

./node_modules/sharp/lib/libvips.js:74:23-70 - Warning: Critical dependency: the request of a dependency is an expression



./node_modules/detect-libc/lib/detect-libc.js:3:15-37 - Error: Module not found: Error: Can't resolve 'os' in '/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-frontend/node_modules/detect-libc/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
        - install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "os": false }

./node_modules/detect-libc/lib/detect-libc.js:4:16-50 - Error: Module not found: Error: Can't resolve 'child_process' in '/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-frontend/node_modules/detect-libc/lib'

./node_modules/detect-libc/lib/detect-libc.js:5:18-43 - Error: Module not found: Error: Can't resolve 'fs' in '/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-frontend/node_modules/detect-libc/lib'

./node_modules/image-thumbnail/node_modules/image-size/dist/index.js:40:11-24 - Error: Module not found: Error: Can't resolve 'fs' in '/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-frontend/node_modules/image-thumbnail/node_modules/image-size/dist'

./node_modules/image-thumbnail/node_modules/image-size/dist/index.js:42:13-28 - Error: Module not found: Error: Can't resolve 'path' in '/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-frontend/node_modules/image-thumbnail/node_modules/image-size/dist'`

**Comment by Th-Barth** [comment]
I get the same errors like grapevinegizmos. I take a new photo from Capacitor.getPhoto and want to save the data as a thumbnail. 

`
// Create a new file from a capture image
  async saveImage(photo: Photo) {
    const imageThumbnail = require('image-thumbnail');

    const base64_data = await this.readAsBase64(photo);
    
    let options = { width: 200, height: 200, responseType: 'base64', jpegOptions: { force:true, quality:60 } };
    
    try {
      const thumbnail_data = await imageThumbnail(base64_data, options);
      const fileName = new Date().getTime() + '.jpeg';
      
      const savedFile = await Filesystem.writeFile({
        path: `${IMAGE_DIR}/${fileName}`,
        data: thumbnail_data,
        directory: Directory.Data
      });

      this.loadFiles();
      
    } catch (error) {
      console.error("saveImage() Error:"+error);  
    }
    
  }
`

The errors appear just by adding the code line "const imageThumbnail = require('image-thumbnail'); "

Is there no solution yet? I wonder why the author didnt give an answer to this probem. Is this project dead?

**Comment by onildoaguiar** [comment]
Sorry Guys, but image-thumbnail is a package server-side only. I'll update the package description.
