### ISSUE TITLE
Segfault with Libvips

### ISSUE THREAD

**Issue by PeterPilley** [onildoaguiar/image-thumbnail#78]
Hi I am using this with Electron.

I am generating a base64 thumbnail as a gallery view with 100 images per page. (thumbnails are generated when page is accessed).
here is an example on how I am calling the function
`
async function generate(target){
    let thumbnailOptions = { percentage: 25, responseType: 'base64', jpegOptions: 100, failOnError: false }
    let thumbnail = await imageThumbnail(`${target}`, thumbnailOptions);
    return thumbnai
}
`
I have not been able to identify the exact cause, but the segfault happens when the thumbnails are being rendered and it is reporting a segfault within dmesg.

It originally happened when I specified the width as a static size as opposed to a percentage, following the change to percentage that cleared up. Now I think it is happening maybe on larger files, files above 100KB.

The dmesg log is not to helpful
electron[2309168]: segfault at 42c80010 ip 00007fc260638a31 sp 00007fff823d2cf0 error 6 in libvips-cpp.so.42[7fc25faf9000+c9e000]

Thanks heaps for the module though it is frickin awesome.

**Comment by PeterPilley** [comment]
Didnt manage to work out what was causing this, however playing with the percentage seemed to cause the error to go away.

**Comment by onildoaguiar** [comment]
Hi @PeterPilley  , I believe this issue should be raised in the [Sharp](https://github.com/lovell/sharp) repository. This library is just a wrapper.
