### ISSUE TITLE
Image thumbnail sharp library cause some fail

### ISSUE THREAD

**Issue by piotrzarzycki21** [onildoaguiar/image-thumbnail#8]
Hello,

I just update library to the newest one and I'm getting fail related to I think an older version of "sharp": "^0.19.0" library. Is it possible to update that library and release another version of image-thumbnail?

**Comment by onildoaguiar** [comment]
Hello @piotrzarzycki21,

Thanks for open the issue. I updated the version of "sharp" in the version 1.0.4 of image-thumbnail.
