### ISSUE TITLE
Add background color support

### ISSUE THREAD

**Issue by VadimBykov** [onildoaguiar/image-thumbnail#85]
Sharp when resizing allows background color to be specified.  Support it , please.

**Comment by curuvar** [comment]
This would be an extremely useful change.  Please support it or merge the pull request that does.

**Comment by onildoaguiar** [comment]
Hi @VadimBykov and @curuvar,

Thank you for bringing this up! I agree that supporting background color when resizing images with Sharp would be a valuable feature.

I’ve reviewed the pull request that addresses this enhancement and will be deploying a new version that includes this feature soon. Your patience is appreciated.

If you have any further questions or need additional modifications, feel free to let me know!

Best regards,
Onildo Aguiar
